import type { WorkItemDto } from '@/lib/types';
import { renderMarkdownToHtml } from '@/lib/markdown';
import { CommentsSection } from './CommentsSection';

interface OverviewSectionProps {
  item?: WorkItemDto;
  projectSlug?: string;
}

export function OverviewSection({ item, projectSlug }: OverviewSectionProps) {
  const html = renderMarkdownToHtml(item?.body || '');
  return (
    <div data-testid="overview-section" className="px-8 py-6 max-w-[920px]">
      <div className="flex flex-wrap gap-1.5 mb-5">
        {item?.dependsOn && item.dependsOn.length > 0 && (
          <div className="text-[12px] text-fg-3">
            <span className="font-medium text-fg-2">Depends on:</span>{' '}
            {item.dependsOn.map((d, i) => (
              <span key={d} className="font-mono">
                #{d}
                {i < item.dependsOn.length - 1 ? ', ' : ''}
              </span>
            ))}
          </div>
        )}
        {item?.blocks && item.blocks.length > 0 && (
          <div className="text-[12px] text-fg-3 ml-4">
            <span className="font-medium text-fg-2">Blocks:</span>{' '}
            {item.blocks.map((d, i) => (
              <span key={d} className="font-mono">
                #{d}
                {i < item.blocks.length - 1 ? ', ' : ''}
              </span>
            ))}
          </div>
        )}
      </div>

      <article
        data-testid="overview-body"
        className="prose-fix text-[13.5px]"
        // biome-ignore lint/security/noDangerouslySetInnerHtml: HTML is generated by renderMarkdownToHtml which escapes raw input.
        dangerouslySetInnerHTML={{ __html: html }}
      />

      {item != null && projectSlug != null && (
        <CommentsSection
          projectSlug={projectSlug}
          id={item.externalId}
          externalId={item.externalId}
        />
      )}
    </div>
  );
}
