import { fetchEvents, fetchIssueDiff, fetchPRD, fetchTriageResult } from '@/lib/api';
import { laneForState } from '@/lib/lanes.config';
import { renderMarkdownToHtml } from '@/lib/markdown';
import type {
  AgentEventDto,
  IssueDiffDto,
  PrdReadModelDto,
  TriageResultDto,
  WorkItemDto,
} from '@/lib/types';
import { getPersonaInitials, getPersonaLabel, usePersonaMap } from '@/lib/usePersonaMap';
import { useQuery } from '@tanstack/react-query';
import { useMemo } from 'react';
import { useParams } from 'react-router-dom';
import { parseDiff } from '../lib/code-diff';
import { useIssueCostsBreakdown } from '../lib/costs';
import { buildWorkflowSnapshotCards } from '../lib/sections';
import { CommentsSection } from './CommentsSection';
import { DependenciesSection } from './DependenciesSection';
import { StatCard } from './StatCard';

interface OverviewSectionProps {
  item?: WorkItemDto;
  projectSlug?: string;
}

export function OverviewSection({ item, projectSlug }: OverviewSectionProps) {
  const { slug = 'goose-hub-self', id = '' } = useParams<{ slug: string; id: string }>();
  const html = renderMarkdownToHtml(item?.body ?? '');
  const personaMap = usePersonaMap();

  const lane = item?.state ? (laneForState(item.state) ?? item.state.replace('factory:', '')) : '—';

  const costs = useIssueCostsBreakdown(slug, id);

  const { data: diffData } = useQuery<IssueDiffDto>({
    queryKey: ['issue-diff', slug, id],
    queryFn: () => fetchIssueDiff(slug, id),
    staleTime: 10_000,
    enabled: id !== '',
  });
  const files = useMemo(() => (diffData?.diff ? parseDiff(diffData.diff) : []), [diffData?.diff]);
  const totalAdds = useMemo(() => files.reduce((s, f) => s + f.adds, 0), [files]);
  const totalDels = useMemo(() => files.reduce((s, f) => s + f.dels, 0), [files]);

  const { data: events = [] } = useQuery<AgentEventDto[]>({
    queryKey: ['events', slug, id],
    queryFn: () => fetchEvents(slug, id),
    staleTime: 10_000,
    enabled: id !== '',
  });
  const { data: triage } = useQuery<TriageResultDto | null>({
    queryKey: ['triage', slug, id],
    queryFn: () => fetchTriageResult(slug, id),
    staleTime: 10_000,
    enabled: id !== '',
  });
  const { data: prd } = useQuery<PrdReadModelDto | null>({
    queryKey: ['prd', slug, id],
    queryFn: () => fetchPRD(slug, id),
    staleTime: 10_000,
    enabled: id !== '',
  });
  const workflowCards = useMemo(
    () =>
      buildWorkflowSnapshotCards({
        item,
        triage,
        prd,
        events,
        stageCosts: costs.byStage,
      }),
    [costs.byStage, events, item, prd, triage],
  );

  return (
    <div data-testid="overview-section" className="px-8 py-6 flex flex-col gap-5">
      {/* Section header */}
      <div>
        <div className="text-[10.5px] uppercase tracking-wider text-fg-2 mb-1">01. Overview</div>
        <h2 className="text-[17px] font-semibold text-fg leading-snug truncate">
          What's happening on this task
        </h2>
        <div className="flex items-center gap-3 mt-1.5 text-[12px] text-fg-3">
          <span className="font-mono">#{item?.externalId}</span>
          <span className="text-fg-5">·</span>
          <span>{item?.state ?? '—'}</span>
        </div>
      </div>

      <div className="rounded-lg border border-line bg-bg-elev overflow-hidden">
        <div className="px-4 py-3 border-b border-line bg-bg-elev-2 flex items-center justify-between gap-3">
          <div>
            <div className="text-[10.5px] uppercase tracking-wider text-fg-2">
              Workflow snapshot
            </div>
            <div className="text-[12px] text-fg-3 mt-1">{lane}</div>
          </div>
          <div className="text-[11px] text-fg-3">
            {files.length === 0
              ? 'No diff yet'
              : `${files.length} files · +${totalAdds} / −${totalDels}`}
          </div>
        </div>
        <div className="p-4 grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3">
          {workflowCards.map((card) => (
            <StatCard
              key={card.key}
              label={card.label}
              value={card.value}
              sub={card.sub}
              color={cardColor(card.tone)}
            />
          ))}
        </div>
      </div>

      {/* Main content grid */}
      <div className="grid gap-4">
        {/* Brief card */}
        <div className="rounded-lg border border-line bg-bg-elev overflow-hidden">
          <div className="px-4 py-3 border-b border-line bg-bg-elev-2">
            <div className="text-[10.5px] uppercase tracking-wider text-fg-2">Brief</div>
          </div>
          <div className="px-4 py-4">
            <article
              data-testid="overview-body"
              className="prose-fix text-[13.5px]"
              // biome-ignore lint/security/noDangerouslySetInnerHtml: HTML is generated by renderMarkdownToHtml which escapes raw input.
              dangerouslySetInnerHTML={{ __html: html }}
            />
            {item && (
              <div className="border-t border-line mt-4 pt-3 flex items-center gap-2">
                <span className="inline-flex items-center justify-center w-6 h-6 rounded-full bg-bg-elev-2 border border-line text-[10px] font-semibold text-fg-2 shrink-0">
                  {getPersonaInitials(personaMap, item.lastPersonaId) ?? '?'}
                </span>
                <span className="text-[12px] text-fg-2 truncate">
                  {getPersonaLabel(personaMap, item.lastPersonaId) ?? '—'} · {item.state ?? '—'}
                </span>
              </div>
            )}
          </div>
        </div>
      </div>
      {/* Dependencies */}
      {item != null && projectSlug != null && (
        <DependenciesSection item={item} projectSlug={projectSlug} />
      )}

      {/* Comments card */}
      {item != null && projectSlug != null && (
        <div className="rounded-lg border border-line bg-bg-elev overflow-hidden flex flex-col">
          <div className="px-4 py-3 border-b border-line bg-bg-elev-2 flex items-center justify-between shrink-0">
            <div className="text-[10.5px] uppercase tracking-wider text-fg-2">Comments</div>
          </div>
          <div className="flex-1 overflow-y-auto">
            <CommentsSection
              projectSlug={projectSlug}
              id={item.externalId}
              externalId={item.externalId}
            />
          </div>
        </div>
      )}
    </div>
  );
}

function cardColor(
  tone: 'default' | 'muted' | 'success' | 'warning' | 'danger',
): string | undefined {
  if (tone === 'muted') return 'var(--fg-3)';
  if (tone === 'success') return 'var(--success)';
  if (tone === 'warning') return 'var(--warning)';
  if (tone === 'danger') return 'var(--danger)';
  return undefined;
}
