import type { ProjectConfig, ProjectRepositoryConfig } from '../../core/types.js';

const bitbucketWorkspaces = [
  {
    workspace: 'smartpayCloud',
    repos: [
      'ami-build',
      'ami-build-rabbitmq-ubuntu',
      'ansible-acm-cf',
      'ansible-aws-resource-tags',
      'ansible-bastion-cf',
      'ansible-datadog-lambda-logs',
      'ansible-dummy-cf',
      'ansible-ecs-task-cf',
      'ansible-kms-cf',
      'ansible-modules',
      'ansible-pb-acquiring-api',
      'ansible-pb-acquiring-mw-onboarding',
      'ansible-pb-ami-build',
      'ansible-pb-asb-sftp-connector',
      'ansible-pb-aws-odu',
      'ansible-pb-b2c-api',
      'ansible-pb-bcu',
      'ansible-pb-cloud-custodian',
      'ansible-pb-cloudcraft-integration',
      'ansible-pb-cloudtrail',
      'ansible-pb-cloudwatch-archiver',
      'ansible-pb-cognito-infrastructure',
      'ansible-pb-cross-account-monitoring',
      'ansible-pb-cuscal-ingestion',
      'ansible-pb-cuscal-onboarding-relay-api',
      'ansible-pb-cuscal-sftp-connector',
      'ansible-pb-data-lounge',
      'ansible-pb-data-masking-service',
      'ansible-pb-datadog-ec2-monitor',
      'ansible-pb-datadog-iam',
      'ansible-pb-datadog-lambda-logs',
      'ansible-pb-datadog-rds-monitor',
      'ansible-pb-datascrape-api',
      'ansible-pb-device-api',
      'ansible-pb-device-settlement-api',
      'ansible-pb-document-store',
      'ansible-pb-downloads',
      'ansible-pb-ec2-backup',
      'ansible-pb-ec2-image-builder',
      'ansible-pb-ecr',
      'ansible-pb-event-router-service',
      'ansible-pb-file-transfer-api',
      'ansible-pb-fraud-api',
      'ansible-pb-identity-api',
      'ansible-pb-illumio-integration',
      'ansible-pb-infra-boilerplate',
      'ansible-pb-ingestion-api',
      'ansible-pb-integration-account',
      'ansible-pb-lambda-layers',
      'ansible-pb-lambda-sftp',
      'ansible-pb-lambda-warmer',
      'ansible-pb-management',
      'ansible-pb-master-dns',
      'ansible-pb-mw-transactions',
      'ansible-pb-netskope-integration',
      'ansible-pb-netsuite-orchestrator-api',
      'ansible-pb-netsuite-sync',
      'ansible-pb-netsuite-terminal-exports',
      'ansible-pb-networking-account',
      'ansible-pb-oauth-api',
      'ansible-pb-oidc-provider',
      'ansible-pb-patron-api',
      'ansible-pb-pdf-api',
      'ansible-pb-playbook-pipeline',
      'ansible-pb-qr-settlement-file-generation',
      'ansible-pb-rabbitmq-queue-deleter',
      'ansible-pb-reporting-api',
      'ansible-pb-requests-api',
      'ansible-pb-reverse-proxy',
      'ansible-pb-s3-file-exchange',
      'ansible-pb-security-account',
      'ansible-pb-serverless-development',
      'ansible-pb-settlement-api',
      'ansible-pb-slack-approver',
      'ansible-pb-slash-api',
      'ansible-pb-smartconnect-api',
      'ansible-pb-smartconnect-bastion',
      'ansible-pb-smartconnect-console',
      'ansible-pb-smartconnect-dynamodb-stream',
      'ansible-pb-smartconnect-iot',
      'ansible-pb-smartconnect-loadtest',
      'ansible-pb-smartconnect-pos',
      'ansible-pb-smartconnect-qr-onboarding',
      'ansible-pb-smartconnect-rabbitmq',
      'ansible-pb-smartconnect-rabbitmq-simple',
      'ansible-pb-smartconnect-terminal',
      'ansible-pb-stacksets',
      'ansible-pb-statements-api',
      'ansible-pb-tdms-db-lambda',
      'ansible-pb-terminal-proxy',
      'ansible-pb-tir-device-onboarding',
      'ansible-pb-tms-api',
      'ansible-pb-tms-iot',
      'ansible-pb-toi-api',
      'ansible-pb-tower-management',
      'ansible-pb-transaction-archiver',
      'ansible-pb-transaction-reports',
      'ansible-pb-transaction-verification',
      'ansible-pb-transactions',
      'ansible-pipeline-deployer',
      'ansible-sam-deployer',
      'ansible-service-linked-roles-cf',
      'aws-organization-deployable-unit',
      'b2c-frontend',
      'cloud-custodian-rules',
      'develop',
      'elasticsearch-lambdas',
      'infra-tools',
      'merchantportal_frontend',
      'modapptms_nz',
      'nodejs-hardened',
      'nz-b2c-frontend',
      'pipeline-helpers',
      'qr-settlement-file-generation',
      'repo-creator',
      'shared-lambda-layers',
      'smartconnect-bulkexport',
      'smartconnect-docker',
      'smartconnect-healthcheck',
      'smartconnect-qr-onboarding',
      'smartconnect-transaction-monitor-lambda',
      'smartconnect_apiserver',
      'smartconnect_consolebackend',
      'smartconnect_consolefrontend',
      'smartconnect_dataprocessor_lambdas',
      'smartconnect_doshiiserver',
      'smartconnect_platform_pollingapi',
      'smartconnect_qr_onboarding_backend',
      'smartconnect_qr_onboarding_frontend',
      'smartconnect_swissknife',
      'smartconnect_terminalemulator_new',
      'smartconnect_terminalemulator_web',
      'smartconnect_terminalserver',
      'smartconnect_vendapp',
      'smartconnect_vendwebapp',
      'smartpaydev',
      'taxipos',
      'terminal-nginx-proxy',
      'test-repo',
      'testing',
      'till2go-amazon-web',
      'till2go_pos_fusion_app',
    ],
  },
  {
    workspace: 'smartpayplatform',
    repos: [
      'acquiring-api',
      'aes-util',
      'api-client',
      'api-responses',
      'audit',
      'avaya-monitor',
      'b2c-api',
      'bcu',
      'bulk-load-tool',
      'client',
      'cloudwatch-archiver',
      'commons',
      'cup-web',
      'cuscal-onboarding-relay-api',
      'cuscal-xml-generation',
      'data-masking-service',
      'datascrape',
      'db-mssql',
      'db-mysql',
      'db-postgresql',
      'device-api',
      'device-on-boarding-tir',
      'device-settlement-api',
      'device-settlement-dictionary',
      'epay-web',
      'eslint-config-backend',
      'etaxi-voucherscards-web',
      'event-router-service',
      'file-io',
      'file-transfer-api',
      'framework',
      'fraud-api',
      'globalpayments',
      'identity-api',
      'identity-api_forked',
      'incentia',
      'ingestion-api',
      'modapptms_aus',
      'modapptms_nz',
      'moto-settlement',
      'msgprocserv',
      'mw-onboarding',
      'mw-transactions',
      'netsuite-bundle',
      'netsuite-orchestrator-api',
      'nz-acquiring-api',
      'nz-asb-sftp-connector',
      'nz-b2c-api',
      'nz-cuscal-ingestion',
      'nz-cuscal-onboarding-relay-api',
      'nz-cuscal-sftp-connector',
      'nz-datascrape',
      'nz-datascrape-harvester',
      'nz-event-router-service',
      'nz-file-transfer-api',
      'nz-identity-api',
      'nz-ingestion-api',
      'nz-netsuite-orchestrator-api',
      'nz-pdf-api',
      'nz-reporting-api',
      'nz-requests-api',
      'nz-statements-api',
      'nz-tms-api',
      'nz-toi-api',
      'nz-transaction-api',
      'nz-transaction-verification-api',
      'oauth',
      'patron-api',
      'paxkeygen-web',
      'pdf-api',
      'qr_australia',
      'rabbit-queues',
      'requests-api',
      'ridewiseata-client',
      'slash-api',
      'smartconnect-admin-api-client',
      'smartconnect-console-backend',
      'smartconnect-iot',
      'smartpaycardportal',
      'snyk-confluence-jira-sync-cli',
      'sp-integration-tests',
      'spy-cli',
      'statements-api',
      'swaggertest',
      'taxipos-aus-web',
      'taxipos-nz-web',
      'taxiposreceiptscriptparser',
      'tdms-db-lambda',
      'temp-nz-tms-api',
      'tms-api',
      'toi-api',
      'transaction-api',
      'transaction-api-load-tester',
      'transaction-archiver',
      'transaction-dictionary',
      'transaction-verification-api',
    ],
  },
] as const;

const repoRefs = bitbucketWorkspaces.flatMap(({ workspace, repos }) =>
  repos.map((repo) => `${workspace}/${repo}`),
);

const repositories: ProjectRepositoryConfig[] = repoRefs.map((repoRef) => ({
  id: repoId(repoRef),
  repoRef,
  cloneUrl: `git@bitbucket.org:${repoRef}.git`,
  defaultBranch: 'main',
  localPath: `~/code/${repoRef}`,
  role: repoRef.startsWith('smartpayCloud/') ? 'infra' : 'code',
}));

const primaryRepo = {
  cloneUrl: 'git@bitbucket.org:smartpayplatform/acquiring-api.git',
  defaultBranch: 'main',
  localPath: '~/code/smartpayplatform/acquiring-api',
};

const config: ProjectConfig = {
  id: 'shift4-smartpay',
  name: 'Shift4 Smartpay',
  slug: 'shift4-smartpay',
  source: {
    kind: 'local-db',
    stateMachine: 'db',
    integrations: {
      jira: {
        enabled: true,
        baseUrl: 'https://shift4.atlassian.net',
        projectKeys: ['TAS', 'MM'],
        importMode: 'assigned-to-me',
        postBack: { comments: true, transitions: false },
      },
      bitbucket: {
        enabled: true,
        workspaces: bitbucketWorkspaces.map(({ workspace, repos }) => ({
          workspace,
          repos: [...repos],
        })),
        postBack: { pullRequests: true, comments: true },
      },
    },
  },
  targetRepo: primaryRepo,
  repositories,
  stack: {
    runtime: 'node',
    packageManager: 'unknown',
    testCommand: 'pnpm test',
    detectedAt: '2026-06-05T00:00:00Z',
  },
  mode: 'supervised',
  storage: { kind: 'local', path: '~/.factory/data/shift4-smartpay' },
  repos: repoRefs,
  agentConfig: {
    runtime: 'auto',
    allowHoldoutOverride: true,
    rolesModels: {
      triager: { primary: 'haiku', fallback: 'haiku', advisor: null },
      griller: { primary: 'opus', fallback: 'sonnet', advisor: null },
      'prd-writer': { primary: 'opus', fallback: 'sonnet', advisor: 'opus' },
      decomposer: { primary: 'sonnet', fallback: 'haiku', advisor: null },
      investigator: { primary: 'opus', fallback: 'sonnet', advisor: null },
      developer: { primary: 'sonnet', fallback: 'haiku', advisor: 'opus' },
      qa: { primary: 'sonnet', fallback: null, advisor: null },
      reviewer: { primary: 'sonnet', fallback: null, advisor: null },
      retrospector: { primary: 'sonnet', fallback: 'haiku', advisor: null },
      researcher: { primary: 'opus', fallback: 'sonnet', advisor: null },
      auditor: { primary: 'opus', fallback: 'sonnet', advisor: null },
      assistant: { primary: 'sonnet', fallback: 'haiku', advisor: null },
    },
    fallbackPolicy: {
      critical: 'same-tier-only',
      high: 'same-tier-only',
      medium: 'allow-down-tier',
      low: 'allow-down-tier',
    },
    advisorMode: {
      enabled: true,
      triggerOn: { priorities: ['critical', 'high'] },
      maxAdvisorBudgetUsd: 1,
      disableInAutonomous: true,
    },
    retrospectivePolicy: {
      defaultTier: 'light',
      deepTriggers: [
        'qa-failed',
        'retries-ge-2',
        'budget-exceeded',
        'needs-human',
        'priority-high',
        'priority-critical',
        'first-run-of-skill',
      ],
    },
    coachPolicy: {
      enabled: false,
      consistencyThreshold: 0.8,
      minLifecycles: 3,
    },
  },
  budgets: {
    dailyTokens: 50_000_000,
    maxParallelAgents: 3,
    maxScoutAgents: 4,
    maxRetries: 2,
    perBashCommandMaxSeconds: 120,
    perWorkflowMaxUsd: 10,
    perAgentMaxUsd: 10,
    perAdvisorMaxUsd: 2,
  },
  governance: {
    immutablePaths: [
      'MISSION.md',
      'FACTORY_RULES.md',
      'CLAUDE.md',
      'target-projects/**/MISSION.md',
      'target-projects/**/FACTORY_RULES.md',
      'target-projects/**/project.config.ts',
      'target-projects/**/personas/**',
    ],
  },
  isolation: { mode: 'native' },
  archiveAfterDays: 7,
  visibility: 'always_visible',
  machineScope: undefined,
  colorStripe: '#0ea5e9',
  activeMilestone: undefined,
  qaE2eMode: 'off',
  playwrightReproEnabled: false,
  evidencePostEnabled: true,
};

function repoId(repoRef: string): string {
  return repoRef
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export default config;
