#!/usr/bin/env tsx
/**
 * Generate docs/inventory.md — a single-page map of every package, slice,
 * skill, app, and target-project. Auto-regenerated; do not hand-edit the
 * output file.
 *
 * Usage:
 *   pnpm manifest          # writes docs/inventory.md
 *   pnpm manifest --check  # exits non-zero if the file would change (CI)
 *
 * The point of this file is to stop hand-maintaining lists of slices/skills/
 * packages in README.md and CLAUDE.md. Filesystem is the source of truth;
 * this script just renders it.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export type Section = 'core' | 'slices' | 'skills' | 'apps' | 'target-projects';

export interface Entry {
  section: Section;
  name: string;
  hasReadme: boolean;
  summary: string;
}

const SECTION_DIRS: Record<Section, string> = {
  core: 'core',
  slices: 'slices',
  skills: 'skills',
  apps: 'apps',
  'target-projects': 'target-projects',
};

const SECTION_ORDER: Section[] = ['apps', 'core', 'slices', 'skills', 'target-projects'];

export function extractSummary(md: string): string {
  if (!md) return '';
  const lines = md.split('\n');
  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith('#')) continue;
    return line;
  }
  return lines[0]?.trim() ?? '';
}

function readReadme(dir: string): { hasReadme: boolean; summary: string } {
  const readmePath = path.join(dir, 'README.md');
  if (!fs.existsSync(readmePath)) return { hasReadme: false, summary: '' };
  const md = fs.readFileSync(readmePath, 'utf8');
  return { hasReadme: true, summary: extractSummary(md) };
}

export function gatherEntries(repoRoot: string): Entry[] {
  const entries: Entry[] = [];
  for (const section of SECTION_ORDER) {
    const dir = path.join(repoRoot, SECTION_DIRS[section]);
    if (!fs.existsSync(dir)) continue;
    const children = fs.readdirSync(dir, { withFileTypes: true });
    for (const child of children) {
      if (!child.isDirectory()) continue;
      if (child.name.startsWith('.') || child.name === 'node_modules') continue;
      const childPath = path.join(dir, child.name);
      const { hasReadme, summary } = readReadme(childPath);
      entries.push({ section, name: child.name, hasReadme, summary });
    }
  }
  return entries;
}

export function formatManifest(entries: Entry[], opts: { generatedAt: string }): string {
  const lines: string[] = [];
  lines.push('# Inventory');
  lines.push('');
  lines.push(
    'Auto-generated by `scripts/build-manifest.ts` (`pnpm manifest`). Do not edit by hand — your changes will be overwritten on the next run.',
  );
  lines.push('');
  lines.push(`Generated: ${opts.generatedAt}`);
  lines.push('');
  lines.push(
    'A flat, machine-readable map of every package and slice in this repo. The point: AI agents (and you) get a single page to orient before diving in, without trusting hand-maintained lists in CLAUDE.md or README.md.',
  );
  lines.push('');

  const bySection = new Map<Section, Entry[]>();
  for (const e of entries) {
    const list = bySection.get(e.section) ?? [];
    list.push(e);
    bySection.set(e.section, list);
  }

  for (const section of SECTION_ORDER) {
    const list = bySection.get(section);
    if (!list || list.length === 0) continue;
    const missing = list.filter((e) => !e.hasReadme).length;
    lines.push(`## ${section}/ (${list.length} entries, ${missing} missing README)`);
    lines.push('');
    lines.push('| Name | README | Summary |');
    lines.push('|---|---|---|');
    const sorted = [...list].sort((a, b) => a.name.localeCompare(b.name));
    for (const e of sorted) {
      const readmeCell = e.hasReadme ? 'yes' : '**missing**';
      const summary = e.summary || '_(no README)_';
      lines.push(`| \`${e.name}\` | ${readmeCell} | ${summary.replace(/\|/g, '\\|')} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function main(): void {
  const repoRoot = path.resolve(fileURLToPath(import.meta.url), '..', '..');
  const checkMode = process.argv.includes('--check');
  const entries = gatherEntries(repoRoot);
  const out = formatManifest(entries, { generatedAt: new Date().toISOString().split('T')[0] });
  const outPath = path.join(repoRoot, 'docs', 'inventory.md');

  if (checkMode) {
    const existing = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : '';
    const stripDate = (s: string) => s.replace(/^Generated: .+$/m, 'Generated: <date>');
    if (stripDate(existing) !== stripDate(out)) {
      console.error('docs/inventory.md is out of date. Run `pnpm manifest` and commit the result.');
      process.exit(1);
    }
    console.log('docs/inventory.md is up to date.');
    return;
  }

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, `${out}\n`, 'utf8');
  const missing = entries.filter((e) => !e.hasReadme);
  console.log(`Wrote ${outPath}: ${entries.length} entries (${missing.length} missing README).`);
  if (missing.length > 0) {
    for (const e of missing) console.log(`  - ${e.section}/${e.name}`);
  }
}

// Run when invoked directly via tsx (not when imported).
const invokedDirectly = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  main();
}
