import type { ProjectConfig } from '../../core/types.js';

const config: ProjectConfig = {
  id: 'goose-hub-self',
  name: 'Goose Hub (self)',
  slug: 'goose-hub-self',
  source: {
    kind: 'github',
    repo: 'shaunnez/goose-hub',
    stateMachine: 'labels',
  },
  targetRepo: {
    cloneUrl: 'git@github.com:shaunnez/goose-hub.git',
    defaultBranch: 'main',
    localPath: '~/code/goose-hub',
  },
  stack: {
    runtime: 'node',
    packageManager: 'pnpm',
    buildCommand: 'pnpm build',
    testCommand: 'pnpm test --reporter=json',
    lintCommand: 'pnpm lint',
    typecheckCommand: 'pnpm typecheck',
    e2eCommand: 'pnpm test:e2e',
    detectedAt: '2026-04-30T00:00:00Z',
  },
  mode: 'supervised',
  storage: { kind: 'local', path: '~/.factory/data/goose-hub-self' },
  repos: ['shaunnez/goose-hub'],
  agentConfig: {
    runtime: 'claude-cli',
    rolesModels: {
      triager: { primary: 'haiku', fallback: 'haiku', advisor: null },
      griller: { primary: 'opus', fallback: 'sonnet', advisor: null },
      'prd-writer': { primary: 'opus', fallback: 'sonnet', advisor: 'opus' },
      decomposer: { primary: 'sonnet', fallback: 'haiku', advisor: null },
      investigator: { primary: 'opus', fallback: 'sonnet', advisor: null },
      developer: { primary: 'haiku', fallback: 'sonnet', advisor: 'opus' },
      qa: { primary: 'sonnet', fallback: null, advisor: null },
      reviewer: { primary: 'sonnet', fallback: null, advisor: null },
      retrospector: { primary: 'sonnet', fallback: 'haiku', advisor: null },
      researcher: { primary: 'opus', fallback: 'sonnet', advisor: null },
    },
    fallbackPolicy: {
      critical: 'same-tier-only',
      high: 'same-tier-only',
      medium: 'allow-down-tier',
      low: 'allow-down-tier',
    },
    toolAllowlists: {
      triager: { bundles: ['core'], extras: ['work-item-label'] },
      griller: { bundles: ['core'], extras: ['work-item-comment'] },
      'prd-writer': { bundles: ['read', 'core'], extras: ['work-item-comment'] },
      decomposer: { bundles: ['read', 'core', 'workItemAdmin'] },
      investigator: { bundles: ['read', 'core'] },
      developer: { bundles: ['read', 'write', 'shell'] },
      qa: { bundles: ['read', 'shell', 'validate'] },
      reviewer: { bundles: ['read', 'validate'] },
      retrospector: { bundles: ['core'], extras: ['event-read', 'persona-stats'] },
      researcher: { bundles: ['web', 'workItemAdmin'] },
    },
    advisorMode: {
      enabled: true,
      triggerOn: { priorities: ['critical', 'high'] },
      maxAdvisorBudgetUsd: 1,
      disableInAutonomous: true,
    },
    retrospectivePolicy: {
      defaultTier: 'light',
      deepTriggers: [
        'qa-failed',
        'retries-ge-2',
        'budget-exceeded',
        'needs-human',
        'priority-high',
        'priority-critical',
        'first-run-of-skill',
      ],
    },
  },
  budgets: {
    dailyTokens: 5_000_000,
    maxParallelAgents: 3,
    maxRetries: 2,
    maxIssuesPerDayFromNonOwners: 3,
    maxBashSeconds: 120,
    perWorkflowMaxUsd: 10,
    perAgentMaxUsd: 10,
    perAdvisorMaxUsd: 2,
  },
  governance: {
    immutablePaths: [
      'MISSION.md',
      'FACTORY_RULES.md',
      'CLAUDE.md',
      'target-projects/**/MISSION.md',
      'target-projects/**/FACTORY_RULES.md',
      'target-projects/**/project.config.ts',
      'target-projects/**/personas/**',
      'docs/PLAN.md',
    ],
  },
  isolation: { mode: 'native' },
  archiveAfterDays: 7,
  visibility: 'always_visible',
  machineScope: undefined,
  colorStripe: '#7c3aed',
  activeMilestone: 'M11: Dependency-aware Scheduling',
};

export default config;
